# Use root/example as user/password credentials
version : '2.0'

services :

  webWoody:
    image: wt_web:latest
    networks:
      woody_net:
        ipv4_address: 172.18.0.23
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - data-volume: "/home/dev/www:/var/www"

  dbWoody:
    image: wt_db:latest
    restart: always
    networks:
      woody_net:
        ipv4_address: 172.18.0.22
    volumes:
      - data-volume:/var/lib/db

volumes:
  data-volume:

networks:
  woody_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/16
