# Use root/example as user/password credentials
version : '2.0'

services :

  dbWoddy:
    image: dbmysql:latest
    restart: always
    networks:
      woody_net:
        ipv4_address: 172.18.0.22
    volumes:
      - data-volume:/var/lib/db

volumes:
  data-volume:

networks:
  woody_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.18.0.0/16
