# Use root/example as user/password credentials
version : '2.0'

services :

  db:
    image: dbmysql:latest
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8880:6603
