# Use root/example as user/password credentials
version : '2'

services :

  webWoody:
    image: adrien97nini/wt_web:latest
    container_name: webWoody
    restart: always
    networks:
      webDb:
        ipv4_address: 172.18.0.132
      server:
        ipv4_address: 172.18.0.23
    ports:
      - "80:80"
      - "443:443"
    volumes:
      -  /home/mitraillet/www:/var/www
    links:
      - dbWoody

  dbWoody:
    image: adrien97nini/wt_db:latest
    container_name: dbWoody
    restart: always
    networks:
      webDb:
        ipv4_address: 172.18.0.131
    volumes:
      - data-volume:/var/lib/db
      - ./files/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf

volumes:
  data-volume:

networks:
  server:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/25

  webDb:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.128/29

