version: '2'
services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: wt1.ephec-ti.be
    container_name: wt_mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=0
    - ENABLE_POSTGREY=0
    - ENABLE_FETCHMAIL=1
    - ENABLE_POP3=1
    - ONE_DIR=1
    - DMS_DEBUG=1
    - SA_TAG=2.0
    - SA_TAG2=6.31
    - SASL_PASSWD="saslpass"
    - SSL_TYPE=letsencrypt

