version : '2'

services :
  soa:
    image: adrien97nini/wt_soa:latest
    container_name: soa
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./config/named.conf:/etc/bind/named.conf
      - ./config/named.conf.options:/etc/bind/named.conf.options
      - ./config/named.conf.default-zones:/etc/bind/named.conf.default-zones
      - ./config/named.conf.local:/etc/bind/named.conf.local
      - ./config/db.wt1.ephec-ti.be:/etc/bind/db.wt1.ephec-ti.be
      - ./config/db.internal.wt1.ephec-ti.be:/etc/bind/db.internal.wt1.ephec-ti.be